# Generated by Django 4.0.3 on 2022-04-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=30)),
                ('_time', models.IntegerField()),
                ('_amazon_term_list_1D', models.TextField(blank=True)),
                ('_amazon_category_list_1D', models.TextField(blank=True)),
                ('_amazon_sentiment_list_1D', models.TextField(blank=True)),
                ('_reddit_term_list_1D', models.TextField(blank=True)),
                ('_reddit_category_list_1D', models.TextField(blank=True)),
                ('_reddit_sentiment_list_1D', models.TextField(blank=True)),
            ],
        ),
    ]
