# -*- coding: utf-8 -*-
"""base.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SoYc7w3lkxVpDWHKqlJc0YenubG5LFko
"""

import numpy as np
from typing import List


class BaseEmbedder:
    """
    用于创建文档和词嵌入模型的基本模型
    参数:
        embedding_model: 用于提取文档和词嵌入的主要嵌入模型
        word_embedding_model: 仅用于提取词嵌入的嵌入模型。 如果选择了这个模型，那么 `embedding_model` 纯粹用于创建文档嵌入。
    """

    def __init__(self, embedding_model=None, word_embedding_model=None):
        self.embedding_model = embedding_model
        self.word_embedding_model = word_embedding_model

    def embed(self, documents: List[str], verbose: bool = False) -> np.ndarray:
        """
        将包含 n 个文档/单词的列表嵌入到嵌入的 n 维矩阵中
        参数:
            documents: A list of documents or words to be embedded
            verbose: Controls the verbosity of the process

        """
        pass