# -*- coding: utf-8 -*-
"""term.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10C4_6T9k-SLDLZHvLDceSwjbCTp4PQea
"""

pip install keybert

from keybert import KeyBERT
import numpy as np
import pandas as pd
kw_model = KeyBERT()

### def read_data():

 
 # data = pd.read_csv('99.csv')
 
 # data = data.loc[:,['reviews.text']]
  
 # return data

data = [] #接输入接口
df_final = [] #输出
df = pd.DataFrame(data)
df2 = pd.DataFrame()
df2 = df2.assign(terms="")

i = 0
def get_terms(df_1,df_2,i):
  while i < len(df_1):
    review = df_1
    keyword = kw_model.extract_keywords(review, keyphrase_ngram_range=(1, 1), stop_words='english',
                              use_maxsum=False, nr_candidates=20, top_n=3)
    row = keyword[1][0] + ',' + keyword[2][0]
    df_2.loc[i] = row
    i = i + 1
  df_final = pd.concat([df_1,df_2],axis=1)
  return df_final

if __name__=="__main__":
  get_terms(df,df2,i)
  print(df_final[0][0])
