# -*- coding: utf-8 -*-
"""updateterm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ICnEcu9iJDQ893GDZATx9OoPmCRc0-J
"""

pip install keybert
from keybert import KeyBERT
import numpy as np
import pandas as pd
kw_model = KeyBERT()
def get_terms(data):
    df = pd.DataFrame(data)
    df2 = pd.DataFrame()
    df2 = df2.assign(terms="")
    i = 0
    while i < len(df):
      review = df[0][i]
      keyword = kw_model.extract_keywords(review, keyphrase_ngram_range=(1, 1), stop_words='english',
                                use_maxsum=False, nr_candidates=20, top_n=3)
      row = keyword[0][0] + ',' + keyword[1][0]
      df2.loc[i] = row
      i = i + 1
    # df_final = pd.concat([df,df2],axis=1)
    df3 = df2.values
    df3 = df3.tolist()
    return df3
